MS-4, MS-6, MS-10: Group searchable variant effects into translatable categories
phenotips/mendelian-search-application pull request #39
Opened 2017-07-29 00:03 UTC by katpavlova

Authored with @marta- and @sdumitriu

2017-07-29 00:04 UTC, katpavlova commented
@sdumitriu I didn't notice your comment earlier and have since rebased the commits so the context for it was lost.... Could you please clarify which line you're referring to?

2017-07-29 05:31 UTC, sdumitriu requested changes

2017-07-29 05:31 UTC, sdumitriu commented on api/src/main/java/org/phenotips/mendelianSearch/internal/MendelianVariantCategory.java
> +@Component
This annotation only makes sense if it's supposed to be an injectable component implementation, in which case it must also have some other class or interface annotated with `@Role` in its hierarchy. Just remove this annotation.

2017-07-31 17:36 UTC, katpavlova commented on api/src/main/java/org/phenotips/mendelianSearch/internal/MendelianVariantCategory.java
> +@Component
Ok thank you!

2017-07-31 19:07 UTC, closed without merging

2017-07-31 20:52 UTC, katpavlova commented
@sdumitriu Annotation has been removed. @veronikaslc I found some bugs so I closed the PR but they have since been fixed, I have tested the PR quite thoroughly so please review the code when you get a chance to.